# Generated by Django 4.1.2 on 2023-01-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_nb",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
