# Generated by Django 4.1.2 on 2023-01-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_alter_experience_host_alter_experience_perks_and_more"),
        ("medias", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="file",
            new_name="fild",
        ),
        migrations.AlterField(
            model_name="video",
            name="experience",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="experiences.experience"
            ),
        ),
    ]
