# Generated by Django 4.1.2 on 2022-10-21 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_experience_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0004_room_category"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Wishlists",
            new_name="Wishlist",
        ),
    ]
