# Generated by Django 4.1.2 on 2022-10-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="check_output",
            new_name="check_out",
        ),
    ]
