# Generated by Django 4.1.2 on 2023-01-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_alter_experience_host_alter_experience_perks_and_more"),
        ("bookings", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="not_canceled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="experiences.experience",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="kind",
            field=models.CharField(
                choices=[("room", "Room"), ("experience", "Experince")], max_length=15
            ),
        ),
    ]
